backend:
  name: github
  repo: catiarodriguescosta/gatsby-starter-blog
media_folder: static/assets
public_folder: /assets
collections:
  - name: recipe
    label: Recipes
    folder: _data/recipes
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: RecipePost,
        }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: "Meal type"
        name: "meal_type"
        widget: "select"
        multiple: true
        options:
          - { label: "Breakfast", value: "Breakfast" }
          - { label: "Appettizer", value: "Appettizer" }
          - { label: "Main Meal", value: "Main" }
          - { label: "Dessert", value: "Dessert" }
          - { label: "Snack", value: "Snack" }
      - label: "Syn Classification"
        name: "syn_classification"
        widget: "select"
        multiple: true
        options:
          - { label: "Syn Free", value: "Free" }
          - { label: "Very Low Syns", value: "VeryLowSyn" }
          - { label: "Low Syn", value: "LowSyn" }
          - { label: "No Classification", value: "None" }
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: "Ingredients", label: "Ingredients",  widget: "markdown"}
      - { name: "Procedure", label: "Procedure",  widget: "markdown"}
      - label: "Servings"
        name: "servings"
        widget: "number"
        default: 1
        valueType: "int"
        min: 1
        max: 20
        step: 1
      - {label: "Total Syns", name: "total_syns", widget: "string"}
      - {label: "Total HE A", name: "total_hea", widget: "string"}
      - {label: "Total HE B", name: "total_heb", widget: "string"}
      - {label: "Syns by serving", name: "serving_syns", widget: "string"}
      - {label: "HE A by serving", name: "serving_hea", widget: "string"}
      - {label: "HE B by serving", name: "serving_heb", widget: "string"}
      - {label: "Time", name: "time", widget: "string"}
      - { name: body, label: Body, widget: markdown }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
  - name: tips
    label: Tips
    folder: _data/tips
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - {
          label: Template,
          name: template,
          widget: hidden,
          default: TipPost,
        }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - label: Featured Image
        name: thumbnail
        widget: image
        hint: "Image size 1280x800 works best :)"
        required: false
        media_library:
          config:
            multiple: false
      - { name: body, label: Body, widget: markdown }
      - label: Meta Description
        name: metaDescription
        widget: text
        required: false
  
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about"
        file: "site/content/about.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Locations Page"
        name: "locations"
        file: "site/content/locations.yml"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}
